POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "BINGELONG",
    "author": "FALFEL",
    "url": "www.viikonloppu.fi/notInHy",
    "likes": 666,
    "userId": "5b641fb33a0b363978d3751b"
}