POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNleFRpcHMiLCJpZCI6IjViNjk1ZWEzNjNmNmMyNGRjOGExM2FhOSIsImlhdCI6MTUzMzYzMjIyMn0.h7myq6W62XNlnetCUJl2_IOebhb4mj2QNYtYHUCdJwU

{
    "title": "mikaels",
    "author": "riemuava lava",
    "url": "www.Kallis.fi/",
    "likes": 1982,
    "userId": "5b695ea363f6c24dc8a13aa9"
}